[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"

[params.modules.alwaysdark]
  integration = 'core'
  state = "async"
  category = "necessary"